###

GET http://localhost:8080/category
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJzaWxAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlkIjoxLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiNjA5ZmI5MDAtNTI4ZC00NWE5LWI2N2ItNTNhODBkOTNmYzYzIiwiZW1haWwiOiJzaWxAZ21haWwuY29tIiwiY2xpZW50X2lkIjoicmVjb2xsYXIxIn0.x_obR6CEsS5qsoWkJTa107qJ-s4B8eOfVJtoeG55tZE, token_type: bearer, refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJzaWxAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImF0aSI6IjYwOWZiOTAwLTUyOGQtNDVhOS1iNjdiLTUzYTgwZDkzZmM2MyIsImlkIjoxLCJleHAiOjE2Mzc4NzEzNTIsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiIzZDAzZDFmMC1iNjM4LTRkZmItOGNkMS0xYzYyZmUxMWNhNGMiLCJlbWFpbCI6InNpbEBnbWFpbC5jb20iLCJjbGllbnRfaWQiOiJyZWNvbGxhcjEifQ.xZYqr4bDWLOKLFuLerSlw1j_7MbofEfY8flUQmhxtbE
###