POST http://localhost:8080/collection
Accept: application/json
Content-Type: application/json

{
  "idCollection": 2,
  "idCollector": 1,
  "name": "Moneda USA-2000",
  "color": "silver",
  "amount": 2,
  "status": 1,
  "idCategory": 1
}
###
PUT http://localhost:8080/collection
Accept: application/json
Content-Type: application/json

{
"idCollection": 1,
"idCollector": 1,
"name": "Moneda USA-2010",
"color": "silver",
"amount": 0,
"status": 1,
"idCategory": 1
}
###
DELETE http://localhost:8080/collection/3
Accept: application/json
Content-Type: application/json
###
GET http://localhost:8080/collection/1
Accept: application/json
Content-Type: application/json

