###

PUT http://localhost:8080/user/password
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJzaWxAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlkIjoxLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiZWQ0MzM1ZjgtNWVmMC00M2Q2LWE3ZmItYWRiYmViODIyNjVhIiwiZW1haWwiOiJzaWxAZ21haWwuY29tIiwiY2xpZW50X2lkIjoicmVjb2xsYXIxIn0.u3DCJed6KBLKbS6ggk7rtBuwRMND7HUSYYnX5cpaUcc, token_type: bearer, refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJzaWxAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImF0aSI6ImVkNDMzNWY4LTVlZjAtNDNkNi1hN2ZiLWFkYmJlYjgyMjY1YSIsImlkIjoxLCJleHAiOjE2Mzc4NzQ5NjksImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiIzN2VkZTAyOS04MTM2LTRiZGUtYjQ1OC05MzNlMzVjM2I1YzEiLCJlbWFpbCI6InNpbEBnbWFpbC5jb20iLCJjbGllbnRfaWQiOiJyZWNvbGxhcjEifQ.0_uw-IRYLEJFrlIcuMzYzoZNp5iWre8XyjiyUTLzx5E

{
  "oldPassword": "1234abcd",
  "newPassword": "abcd"
}
###